jobs:
  test:
    name: Test on JDK ${{ matrix.java }} OS ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven and generate code coverage
      run: ./mvnw -V --no-transfer-progress -Pgen-javadoc -Pgen-dokka clean package
    - continue-on-error: true
      uses: codecov/codecov-action@v3
      with:
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - ubuntu-20.04
      max-parallel: 16
    timeout-minutes: 20
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
